Pages/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SkillTreeRazorPageBlogSample.Pages
{
    public class DetailModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SkillTreeRazorPageBlogSample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SkillTreeRazorPageBlogSample.Data;
using X.PagedList;
using X.PagedList.Mvc.Core.Common;

namespace SkillTreeRazorPageBlogSample.Pages
{
   
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly RazorPageBlogContext _context;


        public IndexModel(ILogger<IndexModel> logger, RazorPageBlogContext context)
        {
            _logger = logger;
            _context = context;

        }




        public class MyClass
        {
            public Guid Id { get; set; }
            public string CoverPhoto { get; set; }
            public string Title { get; set; }
            public string Body { get; set; }
            public string Tags { get; set; }
            public DateTime CreateDate { get; set; }
        }


        public IEnumerable<MyClass> Article { set; get; }

        [ViewData]
        public string handler { set; get; }   //記錄tag的字串，供tag後的分頁使用
        [ViewData]
        public string tagName { set; get; }   //記錄tag的字串，供tag後的分頁使用
        [ViewData]
        public string search_q { set; get; }  //記錄search的字串，供search後的分頁使用






        //public void OnGet()
        //{
        //    //Articles = _context.Articles.ToList();
        //    Article = _context
        //              .Articles.OrderBy(p=>p.Title)
        //              .Select(d => new MyClass
        //              {
        //                  Id = d.Id,
        //                  CoverPhoto = d.CoverPhoto,
        //                  Title = d.Title,
        //                  Body = d.Body.Substring(0, 200),
        //                  CreateDate = d.CreateDate,
        //                  Tags = d.Tags
        //              })
        //              .ToList();
        //    //Debug.WriteLine( Articles[0].Title );
        //}

        /// <summary>
        /// 
        /// </summary>
        /// <param name="p">頁次</param>
        /// <param name="q">search的字串</param>
        public void OnGet(int? p , string q) {

            var pageIndex = p.HasValue ? p.Value < 1 ? 1 : p.Value : 1;
            var qu = _context.Articles.AsQueryable();
            if (string.IsNullOrWhiteSpace(q) == false) {

                search_q = q;

                qu = qu.Where(p => p.Body.Contains(q));

            }


            Article = qu.OrderBy(p => p.Title).Select(p => new MyClass
            {
                Id = p.Id,
                CoverPhoto = p.CoverPhoto,
                Title = p.Title,
                Body = p.Body.Substring(0, 200),
                CreateDate = p.CreateDate,
                Tags = p.Tags

            }).ToPagedList(pageIndex, 5);

        }


        public void OnGetTag(string tag, int? p)
        {
             handler = "tag" ;
             tagName = tag;


            var pageIndex = p.HasValue ? p.Value < 1 ? 1 : p.Value : 1;

            var qu = _context.Articles.AsQueryable();
            if (string.IsNullOrWhiteSpace(tag)==false) {
                qu = qu.Where(p => p.Tags.Contains(tag));
            }

            Article = qu.OrderBy(p => p.Title).Select(p => new MyClass
            {
                Id = p.Id,
                CoverPhoto = p.CoverPhoto,
                Title = p.Title,
                Body = p.Body.Substring(0, 200),
                CreateDate = p.CreateDate,
                Tags = p.Tags

            }).ToPagedList(pageIndex, 5);


        }


















        }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SkillTreeRazorPageBlogSample.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ViewComponents/SearchVcViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SkillTreeRazorPageBlogSample.ViewComponents
{
    public class SearchVcViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            //ViewData.Model = tags.Split(',');

            return View();  //也可以自已指定 View("Index");
        }


    }
}

ViewComponents/TagCloudViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Routing;
using SkillTreeRazorPageBlogSample.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkillTreeRazorPageBlogSample.ViewComponents
{
    public class TagCloudViewComponent : ViewComponent
    {
        private readonly RazorPageBlogContext _context;
       


        public TagCloudViewComponent(RazorPageBlogContext context)
        {
            _context = context;
           
        }


        public IViewComponentResult Invoke()
        {
            ViewData.Model = _context.TagCloud.ToDictionary(d => d.Name, d => d.Amount);
            return View();
        }
    }


}

ViewComponents/TagsVcViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SkillTreeRazorPageBlogSample.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SkillTreeRazorPageBlogSample.ViewComponents
{
    public class TagsVcViewComponent : ViewComponent
    {
        private readonly RazorPageBlogContext _context;

        public TagsVcViewComponent(RazorPageBlogContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke(string tags)
        {
            ViewData.Model = tags.Split(',');

            return View();  //也可以自已指定 View("Index");
        }



    }
}

Pages/Components/SearchVc/Default.cshtml
<h5 class='card-header'>Search</h5>
<div class='card-body'>
    <form asp-page='index' method='get'>
        <div class='input-group'>
            <input type='hidden' name='p' value='1'>
            <input type='text' name='q' class='form-control' placeholder='Search for...'>
            <span class='input-group-btn'>
                <button class='btn btn-secondary' type='submit'>Go!</button>
            </span>
        </div>
    </form>
</div>

Pages/Components/TagCloud/Default.cshtml
@model Dictionary<string, int>
<div class="card my-4">
    <h5 class="card-header">Tag Cloud</h5>
    <div class="card-body">
        <ul class="list-unstyled mb-0">
            @foreach (var item in Model)
            {
                var allDatakk = new Dictionary<string, string> { { "tag", item.Key }, { "p", "1" } };
                //var allDataOther = new
                //{
                //    tag = item.Key,
                //    p=1
                //};

                

                <li class="d-inline">
                    <a asp-page-handler="tag" asp-route-tag="@item.Key" asp-route-p="1">@item.Key (@item.Value)</a>
                    @*<a asp-page-handler="tag" asp-all-route-data="allDatakk">@item.Key (@item.Value)</a>*@
                </li>
            }
        </ul>
    </div>
</div>

Pages/Components/TagsVc/Default.cshtml
@model string[]

@{

    foreach (var item in Model)
    {
        var tagUrl = Url.Page("index", "tag", new { tag = item });
        <a href="@tagUrl" class="btn btn-info">@item</a>
    }
}

Pages/Detail.cshtml
@page
@model SkillTreeRazorPageBlogSample.Pages.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

Pages/Index.cshtml
@page
@model IndexModel
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Core.Common
@using SkillTreeRazorPageBlogSample.Helper


@{
    ViewData["Title"] = "Home page";


}


<h1 class="my-4">
    Page Heading
    <small>Secondary Text</small>
</h1>


@Html.PagedListPager((IPagedList)Model.Article,
    page => Url.Page("index", Model.handler, new { p = page, q=Model.search_q , tag = Model.tagName }), PagingOptionsHelper.FrontEnd)


@foreach (var item in Model.Article)
{
    <div class="card mb-4">
        <img class="card-img-top" src="@item.CoverPhoto" alt="@item.Title">
        <div class="card-body">
            <h2 class="card-title">@item.Title</h2>
            <p class="card-text">@Html.Raw(item.Body)</p>
            <!--TAG 作 模組 Partial view    Razor page(foreach)   -->
            old: @item.Tags
            <br />
            partial: <partial name="_TagsPartial" model="item.Tags"></partial>
            <br />
            tagHelper: <tags-helper>@item.Tags</tags-helper>
            <br />
            viewCommands:<vc:tags-vc tags="@item.Tags"></vc:tags-vc>



        </div>
        <div class="card-footer text-muted">
            Posted on @item.CreateDate.ToString("yyyy-MM-dd") by me
        </div>
    </div>
}

<!-- Pagination -->
@*@Html.PagedListPager(    (IPagedList)Model.Article ,
    page => Url.Action("Index", new { p = page }), PagedListRenderOptions.TwitterBootstrapPagerAligned )*@


@*<ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>*@

<!-- Pagination -->
<!-- Pagination 實作自定義分頁樣式 -->
<!-- Pagination 實作自定義分頁樣式 -->

Pages/Shared/_Layout.cshtml
@addTagHelper *,SkillTreeRazorPageBlogSample


<!DOCTYPE html>
<html lang="zh-tw">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="">
    <meta name="author" content="SkillTree.my">
    <title>@ViewData["Title"] - SkillTreeRazorPageBlogSample</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-page="/Index">SkillTreeRazorPageBlogSample</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container" style="margin-top:30px">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4">
                <!-- Search Widget -->
                <div class="card my-4">


                    <!-- 原始 -->
                    @*<h5 class="card-header">Search</h5>
        <div class="card-body">
            <form asp-page="index" method="get">
                <div class="input-group">
                    <input type="hidden" name="p" value="1">
                    <input type="text" name="q" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="submit">Go!</button>
                    </span>
                </div>
            </form>
        </div>*@
                    <!-- Partial view -->
                    @*<partial name="_searchPartial" />*@
                    <!-- Tag Helper -->
                    <!search></!search>
                    <!-- view Components -->
                    <vc:search-vc></vc:search-vc>






                    <!-- Categories Widget -->
                    @*<div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#">Web Design</a>
                            </li>
                            <li>
                                <a href="#">HTML</a>
                            </li>
                            <li>
                                <a href="#">Freebies</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#">JavaScript</a>
                            </li>
                            <li>
                                <a href="#">CSS</a>
                            </li>
                            <li>
                                <a href="#">Tutorials</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>*@
                    
    
                    <!-- Categories Widget -->
                    <!-- Tag Helper -->
                    <tag-cloud-tt-helper></tag-cloud-tt-helper>
                    <!-- view Components -->
                    <!vc:tag-cloud></!vc:tag-cloud>







                    <!-- Side Widget -->
                    <div class="card my-4">
                        <h5 class="card-header">Side Widget</h5>
                        <div class="card-body">
                            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
                        </div>
                    </div>

                </div>
        </div>
    </div>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019 <a asp-area="" asp-page="/Privacy">Privacy</a></p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/Shared/_TagsPartial.cshtml
@model string
@{ 

    var tags =Model.Split(",");
    foreach (var item in tags)
    {
        var tagUrl = Url.Page("index", "tag", new { tag = item  });
        <a href="@tagUrl" class="btn btn-info"  >@item</a>
    }
}

Pages/Shared/_searchPartial.cshtml
<h5 class='card-header'>Search</h5>
<div class='card-body'>
    <form asp-page='index' method='get'>
        <div class='input-group'>
            <input type='hidden' name='p' value='1'>
            <input type='text' name='q' class='form-control' placeholder='Search for...'>
            <span class='input-group-btn'>
                <button class='btn btn-secondary' type='submit'>Go!</button>
            </span>
        </div>
    </form>
</div>